from __future__ import annotations

COPY = {
    "EN": {
        "personalized": "PERSONALIZED MEAL PLAN",
        "prepared_for": "Prepared for",
        "nutrition_system": "NUTRITION SYSTEM",
        "plan_glance": "YOUR PLAN AT A GLANCE",
        "current_weight": "Current weight",
        "target_weight": "Target weight",
        "daily_energy": "Daily energy",
        "protein": "Protein",
        "meals_day": "Meals / day",
        "food_style": "Food style",
        "how_to_use": "HOW TO USE YOUR PLAN",
        "how_1_title": "Follow the day's structure",
        "how_1": "Use the listed meals and portions as your daily foundation.",
        "how_2_title": "Use a swap when needed",
        "how_2": "Approved exchanges give you flexibility without turning the plan into guesswork.",
        "how_3_title": "Consistency beats perfection",
        "how_3": "Follow the structure most of the time and use the plan as a repeatable system.",
        "month_map": "YOUR PLAN MAP",
        "week": "Week",
        "primary": "Primary structure",
        "swap_rotation": "Swap rotation",
        "continue_rotation": "Continue rotation",
        "fasting_day": "FASTING DAY",
        "exact": "EXACT",
        "familiar": "FAMILIAR",
        "swap": "SMART SWAP",
        "kcal": "kcal",
        "grocery": "GROCERY SYSTEM",
        "grocery_intro": "Purchase quantities are planning estimates. Adjust for package size, household waste and preference.",
        "buy": "Buy",
        "planned": "Planned",
        "portion_hydration": "PORTION & HYDRATION GUIDE",
        "hydration": "Daily hydration guide",
        "hydration_general": "Coach Hilawe's current guidance: 2-4 L of water per day, adjusted for climate, training and individual needs.",
        "portion_note": "Every meal shows exact grams together with a familiar household portion where the source dataset supports one.",
        "coach_note": "COACH NOTE",
        "coach_text": "Transformation is built by consistency, not perfection. Follow the structure, use the approved swaps when needed, and judge progress across time rather than one meal or one day.",
        "review": "PLAN REVIEW & VERSION",
        "review_required": "This plan requires human review before client delivery.",
        "version": "Version",
        "plan_id": "Plan ID",
        "engine": "Engine",
        "dataset": "Dataset",
        "status": "Status",
        "approved_by": "Approved by",
        "approved_at": "Approved at",
        "warning": "Review note",
        "draft_banner": "DRAFT - FOR COACH REVIEW",
        "footer": "Coach Hilawe Personalized Nutrition",
        "breakfast": "Breakfast",
        "lunch": "Lunch",
        "dinner": "Dinner",
        "snack": "Snack",
        "snack_1": "Snack 1",
        "snack_2": "Snack 2",
        "goal": "Goal",
        "training": "Training",
        "budget": "Food budget",
        "diet": "Dietary pattern",
        "fasting": "Fasting",
        "not_provided": "Not provided",
    },
    "AM": {
        "personalized": "የግል የምግብ ፕላን",
        "prepared_for": "የተዘጋጀለት",
        "nutrition_system": "የአመጋገብ ስርዓት",
        "plan_glance": "የፕላንዎ አጭር ማጠቃለያ",
        "current_weight": "የአሁኑ ክብደት",
        "target_weight": "የታለመ ክብደት",
        "daily_energy": "የቀን ካሎሪ",
        "protein": "ፕሮቲን",
        "meals_day": "ምግብ / ቀን",
        "food_style": "የምግብ ምርጫ",
        "how_to_use": "ፕላኑን እንዴት ይጠቀሙ?",
        "how_1_title": "የቀኑን መዋቅር ይከተሉ",
        "how_1": "በየቀኑ የተጻፉትን ምግቦች እና መጠኖች እንደ ዋና መመሪያዎ ይጠቀሙ።",
        "how_2_title": "ሲያስፈልግ ተቀያሪ ይጠቀሙ",
        "how_2": "የተመረጡ ተቀያሪዎች ከፕላኑ አቅጣጫ ሳይወጡ ተለዋዋጭነት ይሰጡዎታል።",
        "how_3_title": "ወጥነት ከፍጹምነት ይበልጣል",
        "how_3": "ፕላኑን በአብዛኛው ጊዜ በወጥነት ይከተሉ፤ አንድ ምግብ ወይም አንድ ቀን ብቻ በመመልከት ውጤትዎን አይገምግሙ።",
        "month_map": "የፕላኑ የቀናት አቀራረብ",
        "week": "ሳምንት",
        "primary": "ዋና መዋቅር",
        "swap_rotation": "ተቀያሪ ምግቦች",
        "continue_rotation": "የተቀያሪ ስርዓቱን ይቀጥሉ",
        "fasting_day": "የጾም ቀን",
        "exact": "ትክክለኛ መጠን",
        "familiar": "ቀላል የቤት መለኪያ",
        "swap": "ተቀያሪ ምግብ",
        "kcal": "ካሎሪ",
        "grocery": "የሳምንት ግሮሰሪ ዝርዝር",
        "grocery_intro": "የግዢ መጠኖቹ የፕላን ግምቶች ናቸው። እንደ ፓኬጅ መጠን፣ የቤት አጠቃቀም እና ምርጫዎ ያስተካክሉ።",
        "buy": "የሚገዛ",
        "planned": "በፕላኑ",
        "portion_hydration": "የመጠን እና የውሃ መመሪያ",
        "hydration": "የቀን የውሃ መመሪያ",
        "hydration_general": "የአሰልጣኝ ህላዌ አሁን ያለው መመሪያ፦ በቀን 2-4 ሊትር ውሃ፤ እንደ አየር ሁኔታ፣ ልምምድ እና የግል ፍላጎት ይስተካከላል።",
        "portion_note": "በፕላኑ ውስጥ ምንጩ በሚፈቅድበት ቦታ ትክክለኛ የግራም መጠን ከቀላል የቤት መለኪያ ጋር ተቀምጧል።",
        "coach_note": "የአሰልጣኝ ማስታወሻ",
        "coach_text": "ለውጥ የሚገነባው በወጥነት እንጂ በፍጹምነት አይደለም። የፕላኑን መዋቅር ይከተሉ፣ ሲያስፈልግ የተፈቀዱትን ተቀያሪዎች ይጠቀሙ እና ለውጥዎን በጊዜ ሂደት ይገምግሙ።",
        "review": "የፕላን ምርመራ እና ቨርዥን",
        "review_required": "ይህ ፕላን ለደንበኛው ከመላኩ በፊት የሰው ምርመራ ያስፈልገዋል።",
        "version": "ቨርዥን",
        "plan_id": "የፕላን መለያ",
        "engine": "የማመንጫ ስርዓት",
        "dataset": "የመረጃ ስብስብ",
        "status": "ሁኔታ",
        "approved_by": "ያጸደቀው",
        "approved_at": "የጸደቀበት ጊዜ",
        "warning": "የምርመራ ማስታወሻ",
        "draft_banner": "ረቂቅ - ለአሰልጣኝ ምርመራ",
        "footer": "የአሰልጣኝ ህላዌ የግል አመጋገብ",
        "breakfast": "ቁርስ",
        "lunch": "ምሳ",
        "dinner": "እራት",
        "snack": "መክሰስ",
        "snack_1": "መክሰስ 1",
        "snack_2": "መክሰስ 2",
        "goal": "ግብ",
        "training": "ልምምድ",
        "budget": "የምግብ በጀት",
        "diet": "የአመጋገብ አይነት",
        "fasting": "ጾም",
        "not_provided": "አልተሰጠም",
    },
}


def copy_for(language: str) -> dict[str, str]:
    return COPY["AM" if str(language).upper() == "AM" else "EN"]


def slot_label(slot: str, language: str) -> str:
    c = copy_for(language)
    normalized = slot.strip().lower().replace(" ", "_")
    return c.get(normalized, slot)

_DAY_AM = {
    "Monday": "ሰኞ",
    "Tuesday": "ማክሰኞ",
    "Wednesday": "ረቡዕ",
    "Thursday": "ሐሙስ",
    "Friday": "አርብ",
    "Saturday": "ቅዳሜ",
    "Sunday": "እሁድ",
}


def day_label(day_name: str, language: str) -> str:
    if str(language).upper() == "AM":
        return _DAY_AM.get(day_name, day_name)
    return day_name
