"""Coach Hilawe Recipe Calibration Dataset & Standards.

Authoritative calibration sheet for all 28 core recipes:
- Exact cooked yield and standard serving portion
- Ingredients and raw/cooked weights with preparation notes
- Explicit cooking oil and added fat accounting
- Verified macros: kcal, protein (g), carbs (g), fat (g), fiber (g)
- Status: CALIBRATED (Verified by Coach Hilawe Semma)
"""
from __future__ import annotations

from typing import Any

RECIPE_CALIBRATIONS: dict[str, dict[str, Any]] = {
    "R001": {
        "recipe_id": "R001",
        "recipe_name_en": "Coach Hilawe Shiro Wot",
        "recipe_name_am": "የአሰልጣኝ ህላዌ ሽሮ ወጥ",
        "fasting": True,
        "fish": False,
        "meal_role": "Primary Lentil/Legume Stew",
        "cooked_yield_g": 900.0,
        "serving_g": 225.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 316.8,
            "protein_g": 13.3,
            "carbs_g": 42.4,
            "fat_g": 12.5,
            "fibre_g": 8.2,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R002": {
        "recipe_id": "R002",
        "recipe_name_en": "Coach Hilawe Misir Wot",
        "recipe_name_am": "የአሰልጣኝ ህላዌ ምስር ወጥ",
        "fasting": True,
        "fish": False,
        "meal_role": "High-Protein Lentil Stew",
        "cooked_yield_g": 1200.0,
        "serving_g": 300.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 341.3,
            "protein_g": 20.0,
            "carbs_g": 52.0,
            "fat_g": 7.6,
            "fibre_g": 11.5,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R003": {
        "recipe_id": "R003",
        "recipe_name_en": "Coach Hilawe Kik Alicha",
        "recipe_name_am": "የአሰልጣኝ ህላዌ ክክ አልጫ",
        "fasting": True,
        "fish": False,
        "meal_role": "Split Pea Stew",
        "cooked_yield_g": 1150.0,
        "serving_g": 288.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 18.0,
        "oil_weight_per_serving_g": 4.5,
        "macros_per_serving": {
            "kcal": 317.1,
            "protein_g": 17.6,
            "carbs_g": 50.8,
            "fat_g": 5.9,
            "fibre_g": 10.2,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R004": {
        "recipe_id": "R004",
        "recipe_name_en": "Coach Hilawe Atkilt Wot",
        "recipe_name_am": "የአሰልጣኝ ህላዌ አትክልት ወጥ",
        "fasting": True,
        "fish": False,
        "meal_role": "Mixed Vegetable Stew",
        "cooked_yield_g": 1200.0,
        "serving_g": 300.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 213.7,
            "protein_g": 4.6,
            "carbs_g": 39.3,
            "fat_g": 5.4,
            "fibre_g": 6.8,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R005": {
        "recipe_id": "R005",
        "recipe_name_en": "Coach Hilawe Gomen",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የጎመን ወጥ",
        "fasting": True,
        "fish": False,
        "meal_role": "Steamed Collard Greens",
        "cooked_yield_g": 900.0,
        "serving_g": 225.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 121.0,
            "protein_g": 5.3,
            "carbs_g": 15.0,
            "fat_g": 6.3,
            "fibre_g": 5.4,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R006": {
        "recipe_id": "R006",
        "recipe_name_en": "Coach Hilawe Fosolia",
        "recipe_name_am": "የአሰልጣኝ ህላዌ ፎሶሊያ በአትክልት",
        "fasting": True,
        "fish": False,
        "meal_role": "Green Beans & Carrot Stew",
        "cooked_yield_g": 1200.0,
        "serving_g": 300.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 147.1,
            "protein_g": 4.2,
            "carbs_g": 23.5,
            "fat_g": 5.7,
            "fibre_g": 6.2,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R007": {
        "recipe_id": "R007",
        "recipe_name_en": "Coach Hilawe Dinich Wot",
        "recipe_name_am": "የአሰልጣኝ ህላዌ ድንች ወጥ",
        "fasting": True,
        "fish": False,
        "meal_role": "Spiced Potato Stew",
        "cooked_yield_g": 1400.0,
        "serving_g": 350.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 306.4,
            "protein_g": 5.8,
            "carbs_g": 54.9,
            "fat_g": 8.1,
            "fibre_g": 6.0,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R008": {
        "recipe_id": "R008",
        "recipe_name_en": "Coach Hilawe Fasting Firfir",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የጾም ፍርፍር",
        "fasting": True,
        "fish": False,
        "meal_role": "Injera Shred Stew Bowl",
        "cooked_yield_g": 800.0,
        "serving_g": 200.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 263.0,
            "protein_g": 6.7,
            "carbs_g": 45.4,
            "fat_g": 6.5,
            "fibre_g": 4.8,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R009": {
        "recipe_id": "R009",
        "recipe_name_en": "Coach Hilawe Fasting Ful",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የጾም ፉል",
        "fasting": True,
        "fish": False,
        "meal_role": "Spiced Fava Bean Bowl",
        "cooked_yield_g": 1100.0,
        "serving_g": 275.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 274.4,
            "protein_g": 15.9,
            "carbs_g": 44.2,
            "fat_g": 4.7,
            "fibre_g": 9.8,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R010": {
        "recipe_id": "R010",
        "recipe_name_en": "Coach Hilawe Chickpea Salad",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የሽምብራ ሰላጣ",
        "fasting": True,
        "fish": False,
        "meal_role": "Cold Chickpea & Veggie Salad",
        "cooked_yield_g": 1000.0,
        "serving_g": 250.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 311.2,
            "protein_g": 14.2,
            "carbs_g": 46.1,
            "fat_g": 9.0,
            "fibre_g": 8.9,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R011": {
        "recipe_id": "R011",
        "recipe_name_en": "Coach Hilawe Lentil Rice Bowl",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የምስር እና ሩዝ ቦውል",
        "fasting": True,
        "fish": False,
        "meal_role": "High-Fiber Grain & Lentil Bowl",
        "cooked_yield_g": 1400.0,
        "serving_g": 350.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 386.2,
            "protein_g": 18.3,
            "carbs_g": 67.5,
            "fat_g": 5.9,
            "fibre_g": 10.5,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R012": {
        "recipe_id": "R012",
        "recipe_name_en": "Coach Hilawe Soy Tibs",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የሶያ ስጋ ጥብስ",
        "fasting": True,
        "fish": False,
        "meal_role": "High-Protein Soy Sauté",
        "cooked_yield_g": 900.0,
        "serving_g": 225.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 18.0,
        "oil_weight_per_serving_g": 4.5,
        "macros_per_serving": {
            "kcal": 265.1,
            "protein_g": 27.7,
            "carbs_g": 26.7,
            "fat_g": 6.0,
            "fibre_g": 7.5,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R013": {
        "recipe_id": "R013",
        "recipe_name_en": "Coach Hilawe Tofu Tibs",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የቶፉ ጥብስ",
        "fasting": True,
        "fish": False,
        "meal_role": "Sautéed Firm Tofu with Aromatics",
        "cooked_yield_g": 1200.0,
        "serving_g": 300.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 361.5,
            "protein_g": 35.9,
            "carbs_g": 14.3,
            "fat_g": 21.4,
            "fibre_g": 4.6,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R014": {
        "recipe_id": "R014",
        "recipe_name_en": "Coach Hilawe Fish Tibs",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የዓሣ ጥብስ",
        "fasting": True,
        "fish": True,
        "meal_role": "High-Protein Sautéed Fish Cubes",
        "cooked_yield_g": 1100.0,
        "serving_g": 275.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 331.7,
            "protein_g": 53.4,
            "carbs_g": 7.0,
            "fat_g": 10.6,
            "fibre_g": 1.8,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R015": {
        "recipe_id": "R015",
        "recipe_name_en": "Coach Hilawe Grilled Tilapia",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የተጠበሰ ቲላፒያ ዓሣ",
        "fasting": True,
        "fish": True,
        "meal_role": "Grilled Whole Fish Fillet",
        "cooked_yield_g": 840.0,
        "serving_g": 210.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 279.8,
            "protein_g": 52.4,
            "carbs_g": 0.5,
            "fat_g": 7.9,
            "fibre_g": 0.1,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R016": {
        "recipe_id": "R016",
        "recipe_name_en": "Coach Hilawe Doro Wot",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የዶሮ ወጥ",
        "fasting": False,
        "fish": False,
        "meal_role": "Traditional Lean Chicken Stew",
        "cooked_yield_g": 1800.0,
        "serving_g": 300.0,
        "servings_per_recipe": 6.0,
        "oil_weight_g": 30.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 448.3,
            "protein_g": 40.8,
            "carbs_g": 13.2,
            "fat_g": 25.3,
            "fibre_g": 2.5,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R017": {
        "recipe_id": "R017",
        "recipe_name_en": "Coach Hilawe Siga Wot",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የበሬ ስጋ ወጥ",
        "fasting": False,
        "fish": False,
        "meal_role": "Traditional Lean Beef Stew",
        "cooked_yield_g": 1700.0,
        "serving_g": 300.0,
        "servings_per_recipe": 5.7,
        "oil_weight_g": 25.0,
        "oil_weight_per_serving_g": 4.4,
        "macros_per_serving": {
            "kcal": 410.9,
            "protein_g": 42.8,
            "carbs_g": 12.6,
            "fat_g": 19.9,
            "fibre_g": 2.3,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R018": {
        "recipe_id": "R018",
        "recipe_name_en": "Coach Hilawe Lean Beef Tibs",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የበሬ ስጋ ጥብስ",
        "fasting": False,
        "fish": False,
        "meal_role": "Pan-Seared Lean Beef with Peppers",
        "cooked_yield_g": 1200.0,
        "serving_g": 250.0,
        "servings_per_recipe": 4.8,
        "oil_weight_g": 24.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 444.8,
            "protein_g": 49.2,
            "carbs_g": 6.1,
            "fat_g": 23.1,
            "fibre_g": 1.5,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R019": {
        "recipe_id": "R019",
        "recipe_name_en": "Coach Hilawe Chicken Tibs",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የዶሮ ስጋ ጥብስ",
        "fasting": False,
        "fish": False,
        "meal_role": "Pan-Seared Chicken Breast Tibs",
        "cooked_yield_g": 1200.0,
        "serving_g": 250.0,
        "servings_per_recipe": 4.8,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 4.2,
        "macros_per_serving": {
            "kcal": 348.9,
            "protein_g": 52.6,
            "carbs_g": 6.1,
            "fat_g": 11.4,
            "fibre_g": 1.5,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R020": {
        "recipe_id": "R020",
        "recipe_name_en": "Coach Hilawe Minchet Abish",
        "recipe_name_am": "የአሰልጣኝ ህላዌ ምንቸት አብሽ",
        "fasting": False,
        "fish": False,
        "meal_role": "Minced Beef Fenugreek Stew",
        "cooked_yield_g": 1400.0,
        "serving_g": 280.0,
        "servings_per_recipe": 5.0,
        "oil_weight_g": 25.0,
        "oil_weight_per_serving_g": 5.0,
        "macros_per_serving": {
            "kcal": 505.2,
            "protein_g": 43.1,
            "carbs_g": 9.9,
            "fat_g": 33.6,
            "fibre_g": 2.2,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R021": {
        "recipe_id": "R021",
        "recipe_name_en": "Coach Hilawe Egg Firfir",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የእንቁላል ፍርፍር",
        "fasting": False,
        "fish": False,
        "meal_role": "Scrambled Eggs with Injera Shreds",
        "cooked_yield_g": 1200.0,
        "serving_g": 300.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 18.0,
        "oil_weight_per_serving_g": 4.5,
        "macros_per_serving": {
            "kcal": 409.8,
            "protein_g": 18.9,
            "carbs_g": 44.6,
            "fat_g": 17.1,
            "fibre_g": 4.6,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R022": {
        "recipe_id": "R022",
        "recipe_name_en": "Coach Hilawe Cooked Lean Kitfo",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የበሰለ የክትፎ ስጋ",
        "fasting": False,
        "fish": False,
        "meal_role": "Minced Beef with Spiced Niter Kibbeh",
        "cooked_yield_g": 830.0,
        "serving_g": 200.0,
        "servings_per_recipe": 4.15,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 4.8,
        "macros_per_serving": {
            "kcal": 479.8,
            "protein_g": 56.1,
            "carbs_g": 0.6,
            "fat_g": 25.8,
            "fibre_g": 0.2,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R023": {
        "recipe_id": "R023",
        "recipe_name_en": "Coach Hilawe Beef Alicha",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የበሬ ስጋ አልጫ",
        "fasting": False,
        "fish": False,
        "meal_role": "Mild Beef & Vegetable Stew",
        "cooked_yield_g": 1600.0,
        "serving_g": 320.0,
        "servings_per_recipe": 5.0,
        "oil_weight_g": 20.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 443.4,
            "protein_g": 43.0,
            "carbs_g": 24.1,
            "fat_g": 18.2,
            "fibre_g": 3.8,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R024": {
        "recipe_id": "R024",
        "recipe_name_en": "Coach Hilawe Ayib Gomen Bowl",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የአይብ እና ጎመን ቦውል",
        "fasting": False,
        "fish": False,
        "meal_role": "High-Protein Fresh Cheese & Greens",
        "cooked_yield_g": 1200.0,
        "serving_g": 300.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 329.2,
            "protein_g": 36.3,
            "carbs_g": 15.5,
            "fat_g": 13.6,
            "fibre_g": 5.2,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R025": {
        "recipe_id": "R025",
        "recipe_name_en": "Coach Hilawe Yogurt Fruit Oat Bowl",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የእርጎ፣ ፍራፍሬ እና አጃ ቦውል",
        "fasting": False,
        "fish": False,
        "meal_role": "High-Protein Breakfast Yogurt Bowl",
        "cooked_yield_g": 1420.0,
        "serving_g": 355.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 0.0,
        "oil_weight_per_serving_g": 0.0,
        "macros_per_serving": {
            "kcal": 446.4,
            "protein_g": 30.6,
            "carbs_g": 60.3,
            "fat_g": 11.2,
            "fibre_g": 6.8,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R026": {
        "recipe_id": "R026",
        "recipe_name_en": "Coach Hilawe Chicken Rice Bowl",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የዶሮ እና ሩዝ ቦውል",
        "fasting": False,
        "fish": False,
        "meal_role": "Post-Workout Chicken Rice & Veggies",
        "cooked_yield_g": 1800.0,
        "serving_g": 450.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 18.0,
        "oil_weight_per_serving_g": 4.5,
        "macros_per_serving": {
            "kcal": 570.5,
            "protein_g": 53.7,
            "carbs_g": 58.0,
            "fat_g": 12.8,
            "fibre_g": 4.2,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R027": {
        "recipe_id": "R027",
        "recipe_name_en": "Coach Hilawe Tuna Pasta",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የቱና ፓስታ",
        "fasting": False,
        "fish": True,
        "meal_role": "High-Protein Tuna Pasta Bowl",
        "cooked_yield_g": 1600.0,
        "serving_g": 400.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 16.0,
        "oil_weight_per_serving_g": 4.0,
        "macros_per_serving": {
            "kcal": 523.7,
            "protein_g": 50.6,
            "carbs_g": 61.7,
            "fat_g": 9.7,
            "fibre_g": 5.8,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
    "R028": {
        "recipe_id": "R028",
        "recipe_name_en": "Coach Hilawe Egg Avocado Toast",
        "recipe_name_am": "የአሰልጣኝ ህላዌ የእንቁላል እና አቮካዶ ቶስት",
        "fasting": False,
        "fish": False,
        "meal_role": "Whole-Grain Egg & Avocado Toast",
        "cooked_yield_g": 950.0,
        "serving_g": 238.0,
        "servings_per_recipe": 4.0,
        "oil_weight_g": 0.0,
        "oil_weight_per_serving_g": 0.0,
        "macros_per_serving": {
            "kcal": 464.2,
            "protein_g": 23.7,
            "carbs_g": 47.2,
            "fat_g": 21.4,
            "fibre_g": 8.5,
        },
        "calibration_status": "CALIBRATED",
        "source_method": "HILAWE_KITCHEN_CALIBRATION_V2",
        "verified_by": "Coach Hilawe Semma",
        "verification_date": "2026-08-25",
        "recipe_version": "2.0",
    },
}


def get_recipe_calibration(recipe_id: str) -> dict[str, Any] | None:
    return RECIPE_CALIBRATIONS.get(recipe_id)
