"""Authoritative state vocabulary for the meal-plan domain.

The customer journey is intentionally split into entity-specific state machines.
A single giant status field would make retries, reviews and future renewal logic
ambiguous. Database CHECK constraints mirror these values.
"""

from enum import StrEnum


class ActorRole(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    REVIEWER = "REVIEWER"
    PAYMENT_VERIFIER = "PAYMENT_VERIFIER"
    WORKER = "WORKER"
    ADMIN = "ADMIN"


class IntakeState(StrEnum):
    COUNTRY_REQUIRED = "COUNTRY_REQUIRED"
    INTAKE_IN_PROGRESS = "INTAKE_IN_PROGRESS"
    HEALTH_REVIEW_REQUIRED = "HEALTH_REVIEW_REQUIRED"
    HEALTH_APPROVED = "HEALTH_APPROVED"
    HEALTH_DECLINED = "HEALTH_DECLINED"
    PROFILE_READY = "PROFILE_READY"
    CHECKOUT_READY = "CHECKOUT_READY"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class HealthReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"


class OrderState(StrEnum):
    CHECKOUT_READY = "CHECKOUT_READY"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    PAYMENT_REVIEW = "PAYMENT_REVIEW"
    PAYMENT_APPROVED = "PAYMENT_APPROVED"
    GENERATION_QUEUED = "GENERATION_QUEUED"
    GENERATING = "GENERATING"
    GENERATION_FAILED = "GENERATION_FAILED"
    REVIEW_PENDING = "REVIEW_PENDING"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    DELIVERY_PENDING = "DELIVERY_PENDING"
    ACTIVE = "ACTIVE"
    RENEWAL_DUE = "RENEWAL_DUE"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class QuoteStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    VERIFYING = "VERIFYING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class GenerationJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class GenerationJobType(StrEnum):
    INITIAL = "INITIAL"
    REGENERATE = "REGENERATE"
    REVISION = "REVISION"


class GenerationStage(StrEnum):
    QUEUED = "QUEUED"
    TARGETS = "TARGETS"
    FOOD_MATCHING = "FOOD_MATCHING"
    WEEK_STRUCTURE = "WEEK_STRUCTURE"
    PORTION_TUNING = "PORTION_TUNING"
    SWAPS = "SWAPS"
    GROCERIES = "GROCERIES"
    DOCUMENTS = "DOCUMENTS"
    REVIEW_HANDOFF = "REVIEW_HANDOFF"
    COMPLETE = "COMPLETE"


class PlanVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_PENDING = "REVIEW_PENDING"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    DELIVERED = "DELIVERED"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"


class PlanVersionSource(StrEnum):
    GENERATED = "GENERATED"
    MANUAL_REPLACEMENT = "MANUAL_REPLACEMENT"
    REVISION = "REVISION"


class ArtifactType(StrEnum):
    DOCX = "DOCX"
    PDF = "PDF"


class ReviewAction(StrEnum):
    APPROVE = "APPROVE"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    REGENERATE = "REGENERATE"
    REPLACE_FILES = "REPLACE_FILES"
    COMMENT = "COMMENT"


class DeliveryStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class DeliveryChannel(StrEnum):
    TELEGRAM_DOCUMENT = "TELEGRAM_DOCUMENT"
    MINI_APP = "MINI_APP"


class CheckinStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    DUE = "DUE"
    SUBMITTED = "SUBMITTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    CLOSED = "CLOSED"
    MISSED = "MISSED"


class RevisionStatus(StrEnum):
    PENDING = "PENDING"
    IN_REVIEW = "IN_REVIEW"
    GENERATION_QUEUED = "GENERATION_QUEUED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


# Compatibility/presentation vocabulary retained from Phase 0. Runtime code should
# prefer IntakeState/OrderState and the entity-specific enums above.
class MealPlanLifecycle(StrEnum):
    COUNTRY_REQUIRED = "COUNTRY_REQUIRED"
    INTAKE_IN_PROGRESS = "INTAKE_IN_PROGRESS"
    HEALTH_REVIEW_REQUIRED = "HEALTH_REVIEW_REQUIRED"
    HEALTH_APPROVED = "HEALTH_APPROVED"
    PROFILE_READY = "PROFILE_READY"
    CHECKOUT_READY = "CHECKOUT_READY"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    PAYMENT_REVIEW = "PAYMENT_REVIEW"
    PAYMENT_APPROVED = "PAYMENT_APPROVED"
    GENERATION_QUEUED = "GENERATION_QUEUED"
    GENERATING = "GENERATING"
    GENERATION_FAILED = "GENERATION_FAILED"
    REVIEW_PENDING = "REVIEW_PENDING"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    DELIVERY_PENDING = "DELIVERY_PENDING"
    ACTIVE = "ACTIVE"
    RENEWAL_DUE = "RENEWAL_DUE"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
